version: '3.8'
services:
  backend:
    build: ./backend
    container_name: zhenyi-backend
    ports:
      - "8000:8000"
    restart: unless-stopped
  frontend:
    build: ./frontend
    container_name: zhenyi-frontend
    depends_on:
      - backend
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host
    restart: unless-stopped